### ISSUE TITLE
New release with nodeSelector support

### ISSUE THREAD

**Issue by mavogel** [joyrex2001/kubedock#100]
Great work 😃  we started extensively using `kubedock` now. Could you cut a release including #97  and #99  as I'd like to pin the version again from `joyrex2001/kubedock:latest` to a tag.

Thank you 👍🏾

**Comment by joyrex2001** [comment]
You are totally right! Just released 0.17.1 with both changes.

https://github.com/joyrex2001/kubedock/releases/tag/0.17.1
