### ISSUE TITLE
Issue: imagePullSecrets Not Set for Pods Created by Testcontainers via Kubedock

### ISSUE THREAD

**Issue by ntqp97** [joyrex2001/kubedock#101]
Description
I have configured Kubedock as follows:
`sidecars:  
  - name: kubedock  
    image: joyrex2001/kubedock:0.17.0  
    args:  
      - server  
      - --reverse-proxy  
      - --unix-socket  
      - --image-pull-secrets nexus-proxy-regcred  
      - /var/run/docker.sock  
    env:  
      - name: NAMESPACE  
        valueFrom:  
          fieldRef:  
            fieldPath: metadata.namespace`
 When running tests using Testcontainers, the pods created by Kubedock do not have the imagePullSecrets set. This results in a failure to pull images from the private registry.

**Comment by joyrex2001** [comment]
The args are incorrect, they should be something lilke:
```
- server
- --reverse-proxy
- --unix-socket
- /var/run/docker.sock
- --image-pull-secrets
- nexus-proxy-regcred
```

**Comment by ntqp97** [comment]
Thanks for your feedback.
