### ISSUE TITLE
Issue Title: Error when copying files to containers using kubedock

### ISSUE THREAD

**Issue by ntqp97** [joyrex2001/kubedock#102]
Description
I am encountering an issue when running tests with Testcontainers while using kubedock. Specifically, an error occurs when trying to copy a file to a container during test setup.

- Here is the full error trace (not using --pre-archive):
`[FAILED] Unexpected error:
      <*fmt.wrapError | 0xc0001c41a0>: 
      create container: can't copy /tmp/1006179066/apisix.yaml to container: Error response from daemon: {"message":"command terminated with exit code 2"}
      {
          msg: "create container: can't copy /tmp/1006179066/apisix.yaml to container: Error response from daemon: {\"message\":\"command terminated with exit code 2\"}",
          err: <*errors.joinError | 0xc0002902e8>{
              errs: [
                  <*errors.joinError | 0xc0002902d0>{
                      errs: [
                          <*fmt.wrapError | 0xc0001c4180>{
                              msg: "can't copy /tmp/1006179066/apisix.yaml to container: Error response from daemon: {\"message\":\"command terminated with exit code 2\"}",
                              err: <errdefs.errSystem>{
                                  error: <*errors.withStack | 0xc000290228>{
                                      error: <*errors.withMessage | 0xc0001c4160>{
                                          cause: <*errors.fundamental | 0xc0002901e0>{msg: ..., stack: ...},
                                          msg: "Error response from daemon",
                                      },
                                      stack: [0x87914c, 0x8784dc, 0x877cd0, 0x85af73, 0x8f8cc3, 0x8f880c, 0x8f227c, 0x907be3, 0x90775b, 0x8fc5b6, 0x8fc598, 0x906708, 0xa7d2f4, 0xaa0f05, 0xa7ceeb, 0x47e661],
                                  },
                              },
                          },
                      ],
                  },
              ],
          },
      }
  occurred`

- Here is the full error trace (Using --pre-archive):

`[FAILED] Unexpected error:
    create container: can't copy /tmp/3234009317/apisix.yaml to container: Error response from daemon: {"message":"pods \"kubedock-n14q3c-apisix-1-bf308844134f\" not found"}
{
    msg: "create container: can't copy /tmp/3234009317/apisix.yaml to container: Error response from daemon: {\"message\":\"pods \\\"kubedock-n14q3c-apisix-1-bf308844134f\\\" not found\"}",
    ...
}
occurred
In [It] at: /src/testutils/containers/apisix/apisix_test.go:42
`
This issue arises during the initialization of a container, when attempting to copy the file /tmp/3234009317/apisix.yaml into the container.

**Comment by joyrex2001** [comment]
Might be a permission issue; the user that runs in the container (and is doing the copy) is not allowed to write on that particular location in the container. Maybe you can also share the relevant logs of kubedock in this issue as well.

**Comment by ntqp97** [comment]
`[GIN] 2024/11/25 - 03:54:49 | 200 |     159.467µs |     10.42.1.113 | HEAD     "/_ping"
I1125 03:54:49.678519       1 util.go:76] Request Headers: http.Header{"Accept-Encoding":[]string{"gzip"}, "User-Agent":[]string{"tc-go/0.33.0"}, "X-Tc-Pp":[]string{"/src/testutils"}, "X-Tc-Sid":[]string{"f8290d15416c4fafb6529aea7c79af58e91c336ee9cb4db10acf698666c0bed5"}}
I1125 03:54:49.678581       1 util.go:77] Request Body:
I1125 03:54:49.678866       1 util.go:100] Response Body: [{"Attachable":true,"Containers":{},"Driver":"bridge","ID":"3459b910281ca6b1fb67c08e14e9ca63dde387408a833eb86e079871acc4b27c","Labels":null,"Name":"host","Scope":"local"},{"Attachable":true,"Containers":{"463ecc17cd57ae80a07d34cda428ecbf10ba1f50f60a6d0f3e3c374e40277539":{"Name":"gav8j5-elasticsearch-1"}},"Driver":"bridge","ID":"4570a605b548ac5f6996672f84ac3cdb47aeb18dc4a686ccf0d7f18b4cc4e6f8","Labels":{"org.testcontainers":"true","org.testcontainers.lang":"go","org.testcontainers.sessionId":"ed0e2c3395474b02f3969c9102c6c691a00d43947d895e9a66fb4620b430d548","org.testcontainers.version":"0.33.0"},"Name":"dbd849f3-787c-479e-a1b2-0a6da1a9ebea","Scope":"local"},{"Attachable":true,"Containers":{},"Driver":"bridge","ID":"56e497dcf639dfa2fcf45ee247ee31d10da31cc7587ab6066e2682570892708f","Labels":null,"Name":"bridge","Scope":"local"},{"Attachable":true,"Containers":{},"Driver":"bridge","ID":"70252a61d6b37975b4d6b672612c92b22409426d7afbc25d6960413109c7b824","Labels":{"org.testcontainers":"true","org.testcontainers.lang":"go","org.testcontainers.sessionId":"f8290d15416c4fafb6529aea7c79af58e91c336ee9cb4db10acf698666c0bed5","org.testcontainers.version":"0.33.0"},"Name":"8db2368d-64ed-449a-8cb5-bbc16eb368a5","Scope":"local"},{"Attachable":true,"Containers":{},"Driver":"bridge","ID":"79f241d66a2a2f00ff9a7ae354efdb48d623831c84d3f93366a1123725aceaa6","Labels":null,"Name":"null","Scope":"local"},{"Attachable":true,"Containers":{"5886ded3b580906178735913ececb51d8a43826e748a24a7aaa7655f07e9a62b":{"Name":"gorse-master"},"658da73cda251c16398c7e86e3eaa310fa88c447d278a58dce3e51a94fafc347":{"Name":"gorse-server"},"9e4e40573462cb274a182829ba2bc6dfbe794ea942b98dd85be99712b7d447a4":{"Name":"gorse-worker"}},"Driver":"bridge","ID":"816e54787798e5d8f568294fc32d70a0ceafef09fc5ab9c68c2f74e920b03261","Labels":{"org.testcontainers":"true","org.testcontainers.lang":"go","org.testcontainers.sessionId":"436e8fb6ff11a96fc14c2acdc599910b3dd32d94c8de04102f61505afb0d2072","org.testcontainers.version":"0.33.0"},"Name":"de4d5498-4f9b-4239-a4b7-4a9758c66cbc","Scope":"local"},{"Attachable":true,"Containers":{"220cd64bcc262396e65479af4332b2e731c2ab72fe8f21ccc2bcdc5092e62a46":{"Name":"qrw8fk-elasticsearch-1"}},"Driver":"bridge","ID":"8ba6eacf6cf592a7ee9dca7dd1850f77c67be2c82110ebdf3e4083d50488fc01","Labels":{"org.testcontainers":"true","org.testcontainers.lang":"go","org.testcontainers.sessionId":"aa0e0a001b4b931e762bfb25aabe2f52dd3b694ac920725814f581b4516be816","org.testcontainers.version":"0.33.0"},"Name":"e74ebef4-ebb5-453d-b082-49aa9ed3b3a2","Scope":"local"}]
[GIN] 2024/11/25 - 03:54:49 | 200 |     451.093µs |     10.42.1.113 | GET      "/networks"
I1125 03:54:49.680234       1 util.go:76] Request Headers: http.Header{"Accept-Encoding":[]string{"gzip"}, "User-Agent":[]string{"tc-go/0.33.0"}, "X-Tc-Pp":[]string{"/src/testutils"}, "X-Tc-Sid":[]string{"f8290d15416c4fafb6529aea7c79af58e91c336ee9cb4db10acf698666c0bed5"}}
I1125 03:54:49.680378       1 util.go:77] Request Body:
[GIN] 2024/11/25 - 03:54:49 | 200 |     337.927µs |     10.42.1.113 | GET      "/images/docker-proxy.vtvlive.vn/elasticsearch:8.13.3/json"
I1125 03:54:49.680509       1 util.go:100] Response Body: {"Architecture":"amd64","Config":{"Env":[]},"ContainerConfig":{"Image":"docker-proxy.vtvlive.vn/elasticsearch:8.13.3"},"Created":"2024-11-25T03:31:48Z","Id":"docker-proxy.vtvlive.vn/elasticsearch:8.13.3","Size":0}
I1125 03:54:49.682096       1 util.go:76] Request Headers: http.Header{"Accept-Encoding":[]string{"gzip"}, "User-Agent":[]string{"tc-go/0.33.0"}, "X-Tc-Pp":[]string{"/src/testutils"}, "X-Tc-Sid":[]string{"f8290d15416c4fafb6529aea7c79af58e91c336ee9cb4db10acf698666c0bed5"}}
I1125 03:54:49.682154       1 util.go:77] Request Body:
I1125 03:54:49.682237       1 util.go:100] Response Body: {"Attachable":true,"Containers":{},"Driver":"bridge","ID":"70252a61d6b37975b4d6b672612c92b22409426d7afbc25d6960413109c7b824","Labels":{"org.testcontainers":"true","org.testcontainers.lang":"go","org.testcontainers.sessionId":"f8290d15416c4fafb6529aea7c79af58e91c336ee9cb4db10acf698666c0bed5","org.testcontainers.version":"0.33.0"},"Name":"8db2368d-64ed-449a-8cb5-bbc16eb368a5","Scope":"local"}
[GIN] 2024/11/25 - 03:54:49 | 200 |     175.319µs |     10.42.1.113 | GET      "/networks/8db2368d-64ed-449a-8cb5-bbc16eb368a5?verbose=true"
I1125 03:54:49.684685       1 util.go:76] Request Headers: http.Header{"Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"2177"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"tc-go/0.33.0"}, "X-Tc-Pp":[]string{"/src/testutils"}, "X-Tc-Sid":[]string{"f8290d15416c4fafb6529aea7c79af58e91c336ee9cb4db10acf698666c0bed5"}}
I1125 03:54:49.684779       1 util.go:77] Request Body: {"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"9200/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["discovery.type=single-node"],"Cmd":null,"Image":"docker-proxy.vtvlive.vn/elasticsearch:8.13.3","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{"org.testcontainers":"true","org.testcontainers.lang":"go","org.testcontainers.sessionId":"f8290d15416c4fafb6529aea7c79af58e91c336ee9cb4db10acf698666c0bed5","org.testcontainers.version":"0.33.0"},"HostConfig":{"Binds":null,"ContainerIDFile":"","LogConfig":{"Type":"","Config":null},"NetworkMode":"","PortBindings":{"9200/tcp":[{"HostIp":"","HostPort":""}]},"RestartPolicy":{"Name":"","MaximumRetryCount":0},"AutoRemove":false,"VolumeDriver":"","VolumesFrom":null,"ConsoleSize":[0,0],"CapAdd":null,"CapDrop":null,"CgroupnsMode":"","Dns":null,"DnsOptions":null,"DnsSearch":null,"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Cgroup":"","Links":null,"OomScoreAdj":0,"PidMode":"","Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"SecurityOpt":null,"UTSMode":"","UsernsMode":"","ShmSize":0,"Isolation":"","CpuShares":0,"Memory":0,"NanoCpus":0,"CgroupParent":"","BlkioWeight":0,"BlkioWeightDevice":null,"BlkioDeviceReadBps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteIOps":null,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpusetCpus":"","CpusetMems":"","Devices":null,"DeviceCgroupRules":null,"DeviceRequests":null,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":null,"OomKillDisable":null,"PidsLimit":null,"Ulimits":null,"CpuCount":0,"CpuPercent":0,"IOMaximumIOps":0,"IOMaximumBandwidth":0,"MaskedPaths":null,"ReadonlyPaths":null},"NetworkingConfig":{"EndpointsConfig":{"8db2368d-64ed-449a-8cb5-bbc16eb368a5":{"IPAMConfig":null,"Links":null,"Aliases":["tt83z8-elasticsearch-1"],"MacAddress":"","DriverOpts":null,"NetworkID":"70252a61d6b37975b4d6b672612c92b22409426d7afbc25d6960413109c7b824","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"DNSNames":null}}}}
I1125 03:54:49.685477       1 util.go:100] Response Body: {"Id":"435053e47f4ad43990b1398383198fe18ee4940bff11356b676a440406e2adf4"}
[GIN] 2024/11/25 - 03:54:49 | 201 |     934.694µs |     10.42.1.113 | POST     "/containers/create?name=tt83z8-elasticsearch-1"
I1125 03:54:49.693174       1 util.go:76] Request Headers: http.Header{"Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"232"}, "Content-Type":[]string{"text/plain"}, "User-Agent":[]string{"tc-go/0.33.0"}, "X-Tc-Pp":[]string{"/src/testutils"}, "X-Tc-Sid":[]string{"f8290d15416c4fafb6529aea7c79af58e91c336ee9cb4db10acf698666c0bed5"}}
I1125 03:54:49.693287       1 util.go:77] Request Body: ����J�0�{{�a����q:��iRf�꾽PEpEe�B�~���凟L��4:�p�	�")���P�C�}-�iN��t]�M8����z�o���|��bV5�
��u��?�U��g�9�C_hb��luf�/2���~;�Â4yeZ%��sƛ�}p&巯RR�9�'��l��)��}�4��K{'��K"�Œ���sp�bO�z�;;;;�����G-
W1125 03:54:49.693864       1 archive.go:38] noOverwriteDirNonDir is not supported, ignoring setting.
E1125 03:54:49.711986       1 util.go:17] error during request[500]: pods "kubedock-tt83z8-elasticsearch-1-435053e47f4a" not found
I1125 03:54:49.712102       1 util.go:100] Response Body: {"message":"pods \"kubedock-tt83z8-elasticsearch-1-435053e47f4a\" not found"}
[GIN] 2024/11/25 - 03:54:49 | 500 |   19.028831ms |     10.42.1.113 | PUT      "/containers/435053e47f4ad43990b1398383198fe18ee4940bff11356b676a440406e2adf4/archive?noOverwriteDirNonDir=true&path=%2F"
I1125 03:54:49.720197       1 util.go:76] Request Headers: http.Header{"Accept-Encoding":[]string{"gzip"}, "User-Agent":[]string{"tc-go/0.33.0"}, "X-Tc-Pp":[]string{"/src/testutils"}, "X-Tc-Sid":[]string{"f8290d15416c4fafb6529aea7c79af58e91c336ee9cb4db10acf698666c0bed5"}}
I1125 03:54:49.720292       1 util.go:77] Request Body:
E1125 03:54:49.720378       1 util.go:17] error during request[403]: cannot delete network, containers attachd
I1125 03:54:49.720437       1 util.go:100] Response Body: {"message":"cannot delete network, containers attachd"}
[GIN] 2024/11/25 - 03:54:49 | 403 |      275.43µs |     10.42.1.113 | DELETE   "/networks/70252a61d6b37975b4d6b672612c92b22409426d7afbc25d6960413109c7b824"
I1125 03:55:18.622684       1 main.go:66] start cleaning lingering objects...
I1125 03:55:18.687211       1 main.go:68] finished cleaning lingering objects...
 `
 
 @joyrex2001 This is logs when I try to copy files to containers using kubedock. Hope you give me more info. Thank you

**Comment by ntqp97** [comment]
```
W1125 08:07:10.486246       1 archive.go:38] noOverwriteDirNonDir is not supported, ignoring setting.
W1125 08:07:10.501963       1 container.go:264] user not set, will run as user defined in image
I1125 08:07:13.641088       1 deploy.go:294] Creating service obc3jk-apisix-1
I1125 08:07:13.689580       1 deploy.go:229] reverse proxy for 37197 to 9080
I1125 08:07:13.690749       1 tcpproxy.go:37] start reverse-proxy 0.0.0.0:37197->10.42.1.34:9080
I1125 08:07:14.101371       1 tcpproxy.go:60] proxying from 127.0.0.1:0.0.0.0:37197 -> 10.42.1.34:9080
I1125 08:07:14.125375       1 copy.go:30] copy archive to 84d7fc57645d:/
I1125 08:07:14.134787       1 exec.go:59] exec kubedock-obc3jk-apisix-1-84d7fc57645d:[tar -xf - -C /]
E1125 08:07:16.352179       1 util.go:17] error during request[500]: command terminated with exit code 2
I1125 08:07:16.352315       1 util.go:100] Response Body: {"message":"command terminated with exit code 2"}
[GIN] 2024/11/25 - 08:07:16 | 500 |  5.866347593s |     10.42.1.113 | PUT      "/containers/84d7fc57645d1fde3cd6b84d8523c1b731d96fbb51cb8d982b616591af0899d8/archive?noOverwriteDirNonDir=true&path=%2F"
[GIN] 2024/11/25 - 08:07:16 | 403 |     406.504µs |     10.42.1.113 | DELETE   "/networks/fa54475e0afeef254f321add44a4a3643fe8566ca3c6dc234459e23eca5b32f6"
I1125 08:07:16.361588       1 util.go:76] Request Headers: http.Header{"Accept-Encoding":[]string{"gzip"}, "User-Agent":[]string{"tc-go/0.33.0"}, "X-Tc-Pp":[]string{"/src/testutils"}, "X-Tc-Sid":[]string{"dac8560eee9bdf2cbbb1fb0ae18cdb56e1ca8feca3622aacdc1c4b7aafc44bd0"}}
I1125 08:07:16.361738       1 util.go:77] Request Body:
E1125 08:07:16.361841       1 util.go:17] error during request[403]: cannot delete network, containers attachd
I1125 08:07:16.361919       1 util.go:100] Response Body: {"message":"cannot delete network, containers attachd"}
I1125 08:07:22.552285       1 main.go:66] start cleaning lingering objects...
I1125 08:07:22.607473       1 main.go:68] finished cleaning lingering objects...
```

this is logs when pre-archive = false

**Comment by pckhoi** [comment]
It probably was a permission issue as most images do not grant access to `/` for the default user. However, we didn't copy the file to the root path ourselves.

We're using https://github.com/testcontainers/testcontainers-go and it looks like they put the original path within the tar archive, copy it to the container's root path, and then extract. Here's the [relevant line](https://github.com/testcontainers/testcontainers-go/blob/v0.33.0/docker.go#L661).

Here's how I suggest we might fix this: [instance.CopyToContainer](https://github.com/joyrex2001/kubedock/blob/35feed3478670be2cc16675cb6a5dec062cfa261/internal/backend/copy.go#L20) should execute the remote command as the root user and grant ownership of the resulting files to the default user. If you also think that's a good solution then we're open to contributing a PR.

**Comment by joyrex2001** [comment]
> Here's how I suggest we might fix this: [instance.CopyToContainer](https://github.com/joyrex2001/kubedock/blob/35feed3478670be2cc16675cb6a5dec062cfa261/internal/backend/copy.go#L20) should execute the remote command as the root user and grant ownership of the resulting files to the default user. If you also think that's a good solution then we're open to contributing a PR.

I don't think this is possible. File copying is doing using an exec within the container, this implies that the user that is doing the copy, is the user that is configured in the container, or in the policies of the k8s cluster.

Adjusting the test-container implementation to copy the files somewhere is probably an easier solution.

**Comment by pckhoi** [comment]
Okay, so we went the pre-archive route instead. It looks like your [extract archive](https://docs.docker.com/reference/api/engine/version/v1.41/#tag/Container/operation/ContainerArchive) handler does not yet handle gzip compressed tar causing it to not work with testcontainers-go. You agree that this can improve yes?

**Comment by joyrex2001** [comment]
I think you are referring to this [api call](https://docs.docker.com/reference/api/engine/version/v1.41/#tag/Container/operation/PutContainerArchive). That call indeed suggests that compressed copies are also supported (although not very clear to me yet how). If this is the problem; the below payload, as in the log, would be a compressed payload?
```
I1125 03:54:49.693287       1 util.go:77] Request Body: <cut>
```
If that's the case, than the current implementation would benefit from that support as well. If not, I don't think adding support would fix the problem.

**Comment by pckhoi** [comment]
Yes, that's what I'm referring to. Compression algorithm can be detected by
reading a few bytes at the beginning of the payload.

Are you referring to kubedock implementation or testcontainers-go
implementation?

**Comment by joyrex2001** [comment]
> Are you referring to kubedock implementation or testcontainers-go
implementation?

Kubedock implementation.

**Comment by pckhoi** [comment]
We happens to fix this already. I'll open a PR later.

**Comment by pckhoi** [comment]
https://github.com/joyrex2001/kubedock/pull/104

**Comment by joyrex2001** [comment]
@pckhoi Great work, thank you. Does this fix this issue as well?

**Comment by pckhoi** [comment]
No problem. There are more issues I'm afraid, so please keep this open for
now.

**Comment by ntqp97** [comment]
If we encounter any further issues, we’ll open a new issue to discuss. Thank you for your support!"
