### ISSUE TITLE
`OneShotStartupCheckStrategy` always returns `StartupStatus.NOT_YET_KNOWN`

### ISSUE THREAD

**Issue by muhimu** [joyrex2001/kubedock#13]
`OneShotStartupCheckStrategy` in testcontainers checks if `finishedAt` is not equal DOCKER_TIMESTAMP_ZERO ("0001-01-01T00:00:00Z"). Kubedock always returns DOCKER_TIMESTAMP_ZERO for finished containers.

**Comment by joyrex2001** [comment]
I have improved the container status api endpoint, can you validate if this solves the issue?
