### ISSUE TITLE
Waiting for running container times out

### ISSUE THREAD

**Issue by dpp23** [joyrex2001/kubedock#15]
The following simple python script fails if running against kubedock, but works against docker:

```
    import docker

    client = docker.from_env(timeout=_DOCKER_CLIENT_TIMEOUT)

    container = client.containers.run(
        "busybox",
        entrypoint="echo",
        command="hey",
        detach=True,
        stdout=True,
        stderr=True,
        tty=False,
        labels={
            "com.joyrex2001.kubedock.deploy-as-job": "true"
        }
    )
    container.wait(timeout=_DOCKER_CLIENT_TIMEOUT)

    print(container.logs(stdout=True, stderr=True, tail=100))
```

I can see the job starting and running successfully, however `container.wait(timeout=_DOCKER_CLIENT_TIMEOUT)` times out even though the pod has finished.

**Comment by joyrex2001** [comment]
I think the root cause is #13.

**Comment by joyrex2001** [comment]
I have improved the container status api endpoint, can you validate if this solves the issue?

**Comment by dpp23** [comment]
@joyrex2001 I've tried to, but hit a different issue that is unrelated - https://github.com/joyrex2001/kubedock/issues/22

**Comment by dpp23** [comment]
I tried cherry-picking 74bfe2b8afb5a981508b6eb39095c6295b7819ce and ae61e80425712c0d78c6f2b5d96dde746d200606 on top of 0.8.2, but it still doesn't work for me.

The following script works fine against `docker`, but timesout if ran against `kubedock`:


```
import docker

_DOCKER_CLIENT_TIMEOUT = 60

client = docker.from_env(timeout=_DOCKER_CLIENT_TIMEOUT)

container = client.containers.run(
    "busybox",
    entrypoint="echo",
    command="hey",
    detach=True,
    stdout=True,
    stderr=True,
    tty=False,
    labels={
        "com.joyrex2001.kubedock.deploy-as-job": "true"
    }
)
container.wait(timeout=_DOCKER_CLIENT_TIMEOUT)

print(container.logs(stdout=True, stderr=True, tail=100))
```

**Comment by dpp23** [comment]
Resolved https://github.com/joyrex2001/kubedock/issues/22 and tested against a build from master, still same timeout.

**Comment by joyrex2001** [comment]
The python sdk doesn't seem to use the status api (which I believe is the case in #13. Not sure why it's blocking yet.

**Comment by joyrex2001** [comment]
The python test now works and waits correctly until the job is completed, can you confirm (and close) if this solves your issue as well?

**Comment by dpp23** [comment]
It works now, thank you! There is a small discrepancy between the behaviour against `docker` vs `kubedock`:

with `docker` `container.wait` returns `{"Error": None, "StatusCode": 0}`, while with `kubedock` you get just `{"StatusCode": 0}` but otherwise it works correctly.
