### ISSUE TITLE
Kubedock liveness / readiness probe?

### ISSUE THREAD

**Issue by rcgeorge23** [joyrex2001/kubedock#16]
Hi there,

More of a question than an issue...

Does kubedock provide a liveness / readiness endpoint?

I would like to run kubedock as a standalone deployment in k8s, so I'm wondering how to configure the k8s liveness / readiness probes.

Thanks!

**Comment by joyrex2001** [comment]
The /_ping endpoint can be used for that. This will return OK when the api is up and running.

Not sure if it makes sense to add another specific one, as this is one is part of the official docker api already.
