### ISSUE TITLE
Issue parsing environment variables where the value contains an `=` (equals) character

### ISSUE THREAD

**Issue by rcgeorge23** [joyrex2001/kubedock#25]
Hi there,

I have come across an issue while trying to set an environment variable that contains an equals character, e.g.

Error from kubedock log:

```
E1004 12:32:00.263399       1 container.go:74] could not parse env SOME_BASE_64_ENCODED_ENV_VARIABLE=MIIJKAIB...JsXVU2syw3EZ7Y=
```

It seems that in `container.go` kubedock determines whether or not an env variable is valid by the presence of only 1 equals character:

```
	for _, e := range co.Env {
		f := strings.Split(e, "=")
		if len(f) != 2 {
			klog.Errorf("could not parse env %s", e)
			continue
		}
		env = append(env, corev1.EnvVar{Name: f[0], Value: f[1]})
	}
```

I wonder if only splitting on the first equals that we encounter would work?

**Comment by rcgeorge23** [comment]
Untested, but I will get this deployed and try it out in the next couple of days...
https://github.com/joyrex2001/kubedock/pull/26

**Comment by joyrex2001** [comment]
It looks good, I'll await your tests before merging :-)

**Comment by rcgeorge23** [comment]
Yep seems to work alright 👍

**Comment by joyrex2001** [comment]
Awesome, thanks! Released https://github.com/joyrex2001/kubedock/releases/tag/0.9.1 containing this fix.
