### ISSUE TITLE
Kubedock does not remove pods after test finishes

### ISSUE THREAD

**Issue by rcgeorge23** [joyrex2001/kubedock#27]
I am using java / junit / testcontainers with Kubedock to spin up a bunch of containers for a test.

After the test has finished, the containers are not removed immediately, but they are eventually cleaned up after an hour or so.

Is this expected behaviour?

To get around this I have added an `afterAll` hook that explicitly removes the pods, which works fine, but I wonder whether something is misconfigured as from the docs it sounds like pod removal should happen automatically after the test has finished.

**Comment by joyrex2001** [comment]
It doesn't look to be the case always and I haven't been able to reproduce myself. Do you have a small project which can trigger this behaviour?

**Comment by rcgeorge23** [comment]
Yep, I will try
