### ISSUE TITLE
How to access to the host?

### ISSUE THREAD

**Issue by olamy** [joyrex2001/kubedock#29]
With testcontainers it's possible to use this `host.testcontainers.internal` to access to the host.
See use case and configuration here https://www.testcontainers.org/features/networking/ .
Is there anything similar?
Thanks a lot for your work!

**Comment by joyrex2001** [comment]
This is basic testcontainers functionality which is supported. Not sure what the question is, if you run kubedock with either reverse-proxy, or port-forward, these should be accessible.

**Comment by olamy** [comment]
General context is a Jenkins build in a kubernetes pod.
My use case is a junit test starting a http2 server then via testcontainer I start this https://github.com/summerwind/h2spec passing the argument `-h host.testcontainers.internal` to run tell h2spec to run the request against the initial pod host.
so when using kubedock `host.testcontainers.internal` is a unknown host.
But I fixed that by adding an env var in pod such this:
```
  - env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
```
so I get the original pod id.
