### ISSUE TITLE
Kubedock sometimes fails to establish reverse proxy

### ISSUE THREAD

**Issue by rcgeorge23** [joyrex2001/kubedock#32]
Hi Vincent,

I have noticed that Kubedock often fails to set up a reverse proxy because the local port that it is trying to bind to is already in use, e.g.

```
E0310 15:02:13.723054       1 deploy.go:206] error setting up port-forward: listen tcp 0.0.0.0:39002: bind: address already in use
I0310 15:02:13.722912       1 deploy.go:192] reverse proxy for 39002 to 8080
I0310 15:02:13.722937       1 tcpproxy.go:33] start reverse-proxy 0.0.0.0:39002->172.20.10.225:8080
```

(I notice that in the version of Kubedock we're using, the log text is slightly wrong. It says `port-forward` but it was actually trying to create a reverse proxy -- this seems to be fixed in the version on master)

From looking at the code I think Kubedock is picking a port at random, and I don't see anywhere where it's checking whether the port is actually free. If that is indeed the case, perhaps it would be good to catch the exception and retry with a different port if a `bind: address already in use` error occurs. What do you think?

Thanks

**Comment by joyrex2001** [comment]
Great find! That makes *a lot of* sense actually and I think this might explain some problems I experienced myself as well.

**Comment by joyrex2001** [comment]
Rewrote the mapping without random, but get ports from the kernel instead. This should solve the mapping to ports that are already in use.

**Comment by rcgeorge23** [comment]
Amazing, thanks so much for getting that fixed! Will test it tomorrow 👍

**Comment by rcgeorge23** [comment]
Looks good so far - we've run a lot of tests today and haven't seen any proxy flakiness, so I'd say this is good to close 👍 
Thanks once again for getting it sorted so quickly.
