### ISSUE TITLE
Docker cp command is failing

### ISSUE THREAD

**Issue by l0rd** [joyrex2001/kubedock#35]
### Problem Description

When trying to run `docker cp` against kubedock I get the following error

```bash
$ docker cp <local_file> <container_name>:<container_folder>
Error response from daemon: {"message":"command terminated with exit code 2"}
```

And from kubedock logs:

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/606959/234121652-0a0b3c5a-d17d-4a51-bd44-504dfce47510.png">

### How to reproduce it

The issue can be reproduced on OpenShift Developer Sandbox (a Red Hat Developer account is required but it's free) using the following link: https://workspaces.openshift.com/f?url=https://github.com/l0rd/micronaut-sample

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/606959/234121792-2b192942-e912-4472-8669-2ad249840dae.png">

### Additional context

When starting a MySQL container using testcontainer it tries to copy a file in the container and fails. That's the reason I am opening this issue. This can be tested running `./gradlew test` in the Red Hat Developer Sandbox workspace linked above.

**Comment by joyrex2001** [comment]
Path handling seems to be incorrect. The error is because it wants to create a file `tmp` in `/`, instead of creating `Dockerfile.dev` in `/tmp`.

This excercise shows the problem better:
```
docker run --name httpd -d python tail -f /dev/null
docker exec httpd mkdir /tmp/test
docker cp ./Dockerfile.dev httpd:/tmp/test
docker exec httpd ls /tmp/test
```
After this, a file called `test` is created, containing the Dockerfile.dev contents.

**Comment by joyrex2001** [comment]
Most likely due to the [not implemented HEAD request](https://github.com/joyrex2001/kubedock/blob/fa49ecb0536457899e8b35fc6d47da15c4722220/internal/server/routes/main.go#L119), which should provide information about the target file/folder.

**Comment by l0rd** [comment]
Thank you @joyrex2001 I verified that it works.

I still have problems running testcontainers for my micronaut application but I think that's a permission problem now: the arbitrary user that runs the mysql container doesn't have the privileges to write in the container root folder. But this is not a kubedock issue so I am closing this one and will investigate if it's possible to configure testcontainers to copy in a different root folder (i.e. running tests as unprivileged user).

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/606959/235102431-169b7c56-0af3-4fd2-b072-4fb60a4c4ddc.png">
