### ISSUE TITLE
Pod names

### ISSUE THREAD

**Issue by rcgeorge23** [joyrex2001/kubedock#36]
Hi Vincent,

Is it possible to have any influence over the names that are assigned to pods when they are created in kubernetes?

Thanks

**Comment by joyrex2001** [comment]
How would you like to see that? I am thinking based on the container name with the container id as suffix?

**Comment by rcgeorge23** [comment]
I was thinking there could be an optional label you could add to a container so users of kubedock could specify something that's meaningful for their use case (with a unique suffix appended to avoid name clashes). If provided, this would be used instead of the default randomly generated name.

For our use case, it would be good to see the name of the service (which is usually part of the image name), the image version and something that groups the pods together as being part of the same test run

**Comment by joyrex2001** [comment]
I have added a label `com.joyrex2001.kubedock.name-prefix` which can be used to add a prefix to the deployed containers. If a name is specifically given to the container, this will be used in the deployment as well. To avoid naming conflicts I left the container id in the name.

**Comment by rcgeorge23** [comment]
Amazing, thanks!
