### ISSUE TITLE
Container not found errors for all containers I start via testcontainers.

### ISSUE THREAD

**Issue by sharkymcdongles** [joyrex2001/kubedock#38]
I probably am doing something wrong, but I am running a kubedock pod. I have testcontainers running via gitlab ci. When it runs it connects find and created containers. I can see it in the logs. However when I check the logs it keeps saying this for all booted containers:

`W0524 18:09:48.023092       1 util.go:64] container status error: pods "kubedock-eohvuhyspkj8-redis-1-d2c8e83115a7" not found`

when I run it with high verbosity it seems to say that the containers were OOMKilled however they were not OOMKilled because I don't see any OOMKilling at all from the kube events nor the container statuses. I even tried setting high limits + requests just to test.

I will try now with 0.10.0 since 0.11.0 is new and perhaps some bug was introduced. Will report back.

My startup commands/args:

```
command: ["/app/kubedock"]
        args: ["server", "-ngitlab-runner", "--reverse-proxy", "--inspector", "--request-memory=1024Mi,1024Mi", "--timeout=4m0s", "--service-account=gitlab-runner-devops"]
```

I also went ahead and gave the service account cluster-admin for all services accounts in this NS just to eliminate other possible reasons.

I am on GKE 1.25.x

**Comment by joyrex2001** [comment]
Were you able to try with 0.10.0 to see if this occurs there as well?

**Comment by sharkymcdongles** [comment]
> Were you able to try with 0.10.0 to see if this occurs there as well? I am unable to reproduce in my setups.

Ya I see the same behaviour on 0.10.0 as well. It is starting the containers using compose from test containers. I also see a bunch of 404 not founds for networks. I tried in both port forward and reverse proxy mode. Not quite sure why it can't find them because I can see the pods running fine without issue and they are even in ready state.

**Comment by joyrex2001** [comment]
Do you have a small test-project which demonstrates the problem?

**Comment by sharkymcdongles** [comment]
> Do you have a small test-project which demonstrates the problem?

I am AFK today but can put something together tomorrow.

**Comment by joyrex2001** [comment]
I am closing this issue, it doesn't seem to be a general issue. Without any specifics, I can't help.
Feel free to re-open with additional info.
