### ISSUE TITLE
Feature request: allow to set node selector & tolerations

### ISSUE THREAD

**Issue by olivierboudet** [joyrex2001/kubedock#42]
This is a feature request.

It would be very useful to allow to set node selector & tolerations when pods are created by kube-dock.

**Comment by joyrex2001** [comment]
What level of flexibility is required? Is a per running kubedock instance setting sufficient, or do you want to be able to control this per container as well? Can you describe the use case a bit more?

**Comment by olivierboudet** [comment]
For my use case, a per running instance is sufficient.
My use case is that all my node pools have taints, so kubedock is unable to start pods in this context. I just need to set a node selector and a toleration to target a node pool to use.

**Comment by joyrex2001** [comment]
I added support for providing a pod-template via `--pod-template <podtemplate.yaml>`. This should allow you to add the required configuration. It can be a minimal pod.yaml, with just the node selector and toleration config.
