### ISSUE TITLE
Configure kubedock with environment variables in combination of arguments

### ISSUE THREAD

**Issue by seboudry** [joyrex2001/kubedock#46]
Hi!

First of all, thank you very much for this project!
Very handful with testcontainers on GKE containerd.

Is it possible to use environment variables in combination of arguments?

With this classic precedence rule:

```
default < environment variable < commande line argument
```

**Comment by joyrex2001** [comment]
Most of the settings can also be configured with environment variables, but unfortunately this is not well documented at the moment. See here: https://github.com/joyrex2001/kubedock/blob/master/cmd/server.go#L87

The environment variable takes precedence over the command line argument.

**Comment by seboudry** [comment]
Thanks, working great!
