### ISSUE TITLE
Best Match target system architecture

### ISSUE THREAD

**Issue by 5V715** [joyrex2001/kubedock#52]
Hey @joyrex2001 ,
really cool stuff thanks for this 🙇 .
recently ran into a little problem and wanted to ask if a change could be proposed.

in https://github.com/joyrex2001/kubedock/blob/master/internal/server/routes/common/images.go#L57
there is no architecture returned resulting in an emulated architecture which runs at somethimes so slow that it doesn't survive the health/ready check. 

my setup is using running as proxy for java-testcontainers

there is already an evaluation of the server/backend architecture. would it make sense to return the backend architecture at that point ?

**Comment by 5V715** [comment]
resulting in the output of this warning when running tests with test-containers
 
```
The architecture 'null' for image 'postgres:15.2-alpine' (ID postgres:15.2-alpine) does not match the Docker server architecture 'amd64'. This will cause the container to execute much more slowly due to emulation and may lead to timeout failures.
```

**Comment by joyrex2001** [comment]
Although it can be updated to match the architecture of the client, or host, it will only remove the warning and not increase performance.

The containers are actually run in k8s itself. Most likely kubernetes needs to pull the image, making a first time use of that container a bit slower. If a node already used the image, it’s cached and performance is likely improved.
