### ISSUE TITLE
Setting properties in pod template on container level

### ISSUE THREAD

**Issue by vladepa** [joyrex2001/kubedock#56]
Hi @joyrex2001,

We are planning to use testcontainers library together with kubedock tool in our CI/CD pipeline on Kubernetes cluster.
The problem is that our IT set some SecurityContext requirements both on pod and containers. As a consequence kubedock is not able to create pods as its specification does not meet requirements. We tried to use pod template option but it is not possible to set properties on container level.
Would it be possible to extend logic for pod template to be able to define properties on container level?

Thank you for your great tool!

Cheers,
Vladislav

**Comment by joyrex2001** [comment]
Added support for templating the containers. If a containers block is present in the pod template, it will use the first provided container as a template for all containers (including sidecars and init containers) it will create inside the pod.
