### ISSUE TITLE
Kubernetes Service not created

### ISSUE THREAD

**Issue by christophd** [joyrex2001/kubedock#57]
The Kubernetes Service is missing when running a Testcontainer (e.g. PostgreSQL) with Kubedock. The container does export the port properly but there is no Service resource created. I tested this with Kubedock v0.14, v0.13 and v0.12 and was not able to get this running. The last version that did work for me is v0.10

Adding `--inspector` option also does not help.

Any hints are much appreciated. Many thanks!

**Comment by joyrex2001** [comment]
I removed it here: https://github.com/joyrex2001/kubedock/commit/625b4aba975211418b50565d1fa113a15ef3adba because I thought it was not used. :-/

**Comment by joyrex2001** [comment]
Reverted the change, can you confirm this is what you expected?

**Comment by christophd** [comment]
I am not tied to the `kd-*` service name but I'd expect that a Service resource is being created when there is an exposed port on the container. I also see that this is currently not working with a NetworkAlias set on the Testcontainers container.

**Comment by joyrex2001** [comment]
How are you using, determining which service to use? The network alias services (named according the that alias) didn't change. Another change that might have impacted you is that kubedock not creates deployments anymore, but pods directly.

**Comment by christophd** [comment]
Ah, now I see what has been missing on my side. Setting `.withNetworkAliases("foo")` on the Testcontainer only is not enough. I also need to set `.withNetwork(Network.newNetwork())` and I was missing this before.

With that in place I do actually see the Kubernetes Service being created properly. Thank you, that works for me! Sorry for the noise!

**Comment by joyrex2001** [comment]
No worries, thanks for reporting. I will leave the default generated service in.
