### ISSUE TITLE
 docker-in-docker (ryuk support) doesn't work testcontainers-dotnet

### ISSUE THREAD

**Issue by jonesbusy** [joyrex2001/kubedock#68]
Hi,

We are using kubedock 0.15.1 on OKD with ryuk support and it works well with testcontainers-java and testcontainers-node modules.

But a behavior is different with testcontainers-dotnet with the bind mount volume.

From reading the code the `dind-sidecar` is added when a target `/var/run/docker.sock` https://github.com/joyrex2001/kubedock/blob/8521b935e972698b04a8e6cf95a87107f2d0b2dc/internal/backend/deploy.go#L503

Works for Java and Node testcontainer module

![ryuk_java](https://github.com/joyrex2001/kubedock/assets/825750/15e190dc-a294-437b-90ff-f78d6d7bed43)

But the .NET implementation fail because not sidecar is created

![ryuk](https://github.com/joyrex2001/kubedock/assets/825750/e625e5fa-4ba2-400a-819a-f342be8ef088)

CI is run on Jenkins pipeline and environment is similar to all implementation

```
pipeline {
  agent {
    kubernetes {
        yaml(
           // dotnet container and kubedock here
        }
    }
  }
  environment {
    ...
    DOCKER_HOST = 'tcp://localhost:2475'
    ...
  }
  ....
}
```

So I suspect something is different from the node and other testcontainer implementation.

But looking at the code the unix socket mount is added correctly : https://github.com/testcontainers/testcontainers-dotnet/blob/develop/src/Testcontainers/Containers/ResourceReaper.cs#L416 and working when running on a docker environment

I'm wonder if it's something similar to https://github.com/joyrex2001/kubedock/issues/30#issuecomment-1866691761 

Let me know if I can provide more information

Thanks!

**Comment by joyrex2001** [comment]
Hi @jonesbusy, thanks for these details. Looks like you were right with regards to it failing due to the missing hostconfig mount support. I added that, and the dind-sidecar is now being created when ryuk is enabled.

**Comment by jonesbusy** [comment]
Hi!

I confirm the issue is resolved using 'latest' container image!

Thanks a lot
