### ISSUE TITLE
Allow to set spec.activeDeadlineSeconds

### ISSUE THREAD

**Issue by lorenzobenvenuti** [joyrex2001/kubedock#70]
Hi,

we're using Kubedock in a multi-tenant cluster where quotas are used to restrict the resources that can be used by each tenant. There are different [quota scopes](https://kubernetes.io/docs/concepts/policy/resource-quotas/) based on the `activeDeadlineSeconds` property: short-lived pods (`activeDeadlineSeconds > 0`) consume resources from the "Terminating" quota while long-lived pods (`activeDeadlineSeconds` not set) consume resources from the "NotTerminating" quota. Currently Kubedock doesn't allow to specify the `activeDeadlineSeconds` property and this results in all the pods consuming resources from the "NotTerminating" quota even if the pod is short-lived (for example, used to run tests based on Testcontainers). We'd like to be able to set `activeDeadlineSeconds`; for example (much like pods request/limit) we could have a cmd line argument for setting the default value and we could use labels to override it.

If you think the feature is worth implementing I can try to put a PR together.

Thanks,

lorenzo

**Comment by jonesbusy** [comment]
Hi,

Thanks for raising this. We have same requirement for terminating and non-terminating pods.

I think we can specify the `activeDeadlineSeconds` using YAML pod template. But I didn't test it.

Would be useful to have this on the command line. 

Regards,

**Comment by joyrex2001** [comment]
Sounds like something useful, feel free to open a pr. Note that you can probably already achieve your goal by using the pod template feature (`--pod-template`), but without the ability to override it via labels.

**Comment by lorenzobenvenuti** [comment]
Created https://github.com/joyrex2001/kubedock/pull/71

Please bear with me, I haven't coded in Go for a while.

Thanks,

lorenzo

**Comment by lorenzobenvenuti** [comment]
Hi @joyrex2001 , are there any upcoming releases? Thanks!

**Comment by joyrex2001** [comment]
@lorenzobenvenuti I expect to release somewhere this or next week.

**Comment by lorenzobenvenuti** [comment]
Ack, tyvm!

**Comment by joyrex2001** [comment]
@lorenzobenvenuti 0.15.3 is just released.

**Comment by lorenzobenvenuti** [comment]
Awesome, thanks a lot!
